---
- name: Install Apache
  hosts: all
  
  tasks:
    - name: Install Apache
      yum: 
        name: " {{ modules }} " 
        vars:
          modules:
          - httpd
          - httpd-devel
        state: present

    - name: Copy configuration files
      copy:
        src: "{{ item['src'] }} "
        dest: "{{ item['dest'] }} "
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: httpd.conf
          dest: /etc/httpd/conf/httpd.conf
        - src: httpd-vhosts.conf
          dest: /etc/httpd/conf/httpd-vhosts.conf        

    - name: Ensure Apache is started and at boot
      service:
        name: httpd
        start: started
        enabled: yes