---
- name: Install Apache
  hosts: all      
  become: yes

  handlers:
    - name: restart Apache
      service: 
        name: httpd
        state: restarted

  tasks:
    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present
      notify: restart Apache

    - name: Add entry into host terminal
      lineinfile:
        dest: "~/.bash_profile"
        line: "#This is only for demo purpose"
      become: no

    - name: Extract variables from hosts
      shell: 'source ~/.bash_profile && echo $PATH'
      register: env_var

    - debug: msg="output from hosts is {{ env_var.stdout }}"

    - name: Ensure apache is running and start at boot
      service:
        name: httpd
        state: started
        enabled: true
    
    - name: Ensure handlers are run immediately
      meta: flush_handlers

      
