---
- hosts: all
  become: yes

  vars_files: 
    - vars.yml

  pre_tasks:
    - name: Update yum cache if needed
      yum: 
        update_cache: true         
    
  handlers:
    - name: Restart solr
      service:
        name: solr
        state: restarted
    
  tasks:
    - name: Install Java
      yum: 
        name: java-1.8.0-openjdk
        state: latest

    - name: Download solr
      get_url:  
        url: "http://apachemirror.wuchna.com/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        checksum: "{{ solr_checksum }}"

    - name: Expand solr
      unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{ solr_version }}/README.txt"

    - name: Run Solr installation script
      command: >
        {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh
        {{ download_dir }}/solr-{{ solr_version }}.tgz
        -i /opt
        -d /var/solr
        -u solr
        -s solr
        -p 8983
        creates= {{ solr_dir }}/bin/solr

    - name: Ensure solr is started and enabeld at boot
      service: 
        name: solr
        state: started
        enabled: yes
