version: '3.3'

services:
  # vault-filesystem:
  #   image: hashicorp/vault-enterprise:1.4.0_ent
  #   ports:
  #     - '8200:8200'
  #   networks: 
  #     - dev-network
  #   environment:
  #     - VAULT_ADDR=http://vault-demo:8200
  #     - VAULT_API_ADDR=http://127.0.0.1:8200
  #   command: server -config=/vault/config/vault-config.json -dev
  #   cap_add:
  #     - IPC_LOCK
  db:
    image: postgres:14.1
    restart: always
    networks: 
      - dev-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /tmp
    ports:
      - '5432:5432'
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes: 
      - ./src/database:/var/lib/postgresql/data
      # copy the sql script to create tables
      # - ./src/database/sample.sql:/docker-entrypoint-initdb.d/create_tables.sql
  app:
    image: vault-app:latest
    networks: 
      - dev-network
    ports:
      - '8080:8080'
    environment:
      - VAULT_ADDR=http://vault-demo:8200
      - PSQL_ADDR=http://vault_db_1:5432
    volumes:
      - .:/src/dev
    depends_on:
      - db
networks:
  dev-network:
    driver: bridge