---
- hosts: all
  become: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: Ensure NTP is installed
      apt: name=ntp state=present
    - name: Ensure NTP is running
      service: name=ntpd state=started enabled=yes